# Generated by Django 3.2.7 on 2021-09-27 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_creacion_columnas_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabeceramodel',
            old_name='tipoCabecera',
            new_name='cabeceraTipo',
        ),
        migrations.RemoveField(
            model_name='cabeceramodel',
            name='fechaCabecera',
        ),
        migrations.AddField(
            model_name='cabeceramodel',
            name='cabeceraFecha',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabeceramodel',
            name='clientes',
            field=models.ForeignKey(db_column='clientes_id', on_delete=django.db.models.deletion.PROTECT, related_name='clienteCabeceras', to='gestion.clientemodel'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteDocumento',
            field=models.CharField(db_column='documento', max_length=12, unique=True, verbose_name='documento del cliente'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteNombre',
            field=models.CharField(db_column='nombre', help_text='Ingresa aqui el nombre', max_length=45, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='detallemodel',
            name='productos',
            field=models.ForeignKey(db_column='productos_id', on_delete=django.db.models.deletion.PROTECT, related_name='productoDetalles', to='gestion.productomodel'),
        ),
    ]
